////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./main.v
//
// Project:	ZBasic, a generic toplevel implementation using the full ZipCPU
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	../../../autofpga/trunk/sw/autofpga ../../../autofpga/trunk/sw/autofpga -o . global.txt bkram.txt buserr.txt clock.txt dlyarbiter.txt flash.txt rtclight.txt rtcdate.txt pic.txt pwrcount.txt rtclight.txt version.txt busconsole.txt zipmaster.txt sdspi.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2017, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
`default_nettype	none
//
//
// Here is a list of defines which may be used, post auto-design
// (not post-build), to turn particular peripherals (and bus masters)
// on and off.  In particular, to turn off support for a particular
// design component, just comment out its respective define below
//
// These lines are taken from the respective @ACCESS tags for each of our
// components.  If a component doesn't have an @ACCESS tag, it will not
// be listed here.
//
// First, the independent access fields for any bus masters
`define	INCLUDE_ZIPCPU
`define	WBUBUS_MASTER
// And then for the independent peripherals
`define	BUSCONSOLE_ACCESS
`define	FLASH_ACCESS
`define	BUSPIC_ACCESS
`define	RTC_ACCESS
`define	BLKRAM_ACCESS
`define	FLASH_ACCESS
`define	SDSPI_ACCESS
//
//
// Then, the list of those things that have dependencies
//
//
`ifdef	RTC_ACCESS
`define	RTCDATE_ACCESS
`endif
`ifdef	SDSPI_ACCESS
`define	SDSPI_SCOPE
`endif
//
// End of dependency list
//
//
//
//
// Finally, we define our main module itself.  We start with the list of
// I/O ports, or wires, passed into (or out of) the main function.
//
// These fields are copied verbatim from the respective I/O port lists,
// from the fields given by @MAIN.PORTLIST
//
module	main(i_clk, i_reset,
		// The QSPI Flash
		o_qspi_cs_n, o_qspi_sck, o_qspi_dat, i_qspi_dat, o_qspi_mod,
		i_cpu_reset,
		// Command and Control port
		i_host_rx_stb, i_host_rx_data,
		o_host_tx_stb, o_host_tx_data, i_host_tx_busy,
		// The SD-Card wires
		o_sd_sck, o_sd_cmd, o_sd_data, i_sd_cmd, i_sd_data, i_sd_detect);
//
// Any parameter definitions
//
// These are drawn from anything with a MAIN.PARAM definition.
// As they aren't connected to the toplevel at all, it would
// be best to use localparam over parameter, but here we don't
// check
	//
	//
	// Variables/definitions needed by the ZipCPU BUS master
	//
	//
	// A 32-bit address indicating where teh ZipCPU should start running
	// from
	localparam	RESET_ADDRESS = 32'h01000000;
	//
	// The number of valid bits on the bus
	localparam	ZIP_ADDRESS_WIDTH = 30;	// Zip-CPU address width
	//
	// Number of ZipCPU interrupts
	localparam	ZIP_INTS = 16;
	//
	// ZIP_START_HALTED
	//
	// A boolean, indicating whether or not the ZipCPU be halted on startup?
	localparam	ZIP_START_HALTED=1'b1;
//
// The next step is to declare all of the various ports that were just
// listed above.  
//
// The following declarations are taken from the values of the various
// @MAIN.IODECL keys.
//
	input	wire		i_clk, i_reset;
	// The QSPI flash
	output	wire		o_qspi_cs_n, o_qspi_sck;
	output	wire	[3:0]	o_qspi_dat;
	input	wire	[3:0]	i_qspi_dat;
	output	wire	[1:0]	o_qspi_mod;
	input	wire		i_cpu_reset;
	input	wire		i_host_rx_stb;
	input	wire	[7:0]	i_host_rx_data;
	output	wire		o_host_tx_stb;
	output	wire	[7:0]	o_host_tx_data;
	input	wire		i_host_tx_busy;
	// SD-Card declarations
	output	wire		o_sd_sck, o_sd_cmd;
	output	wire	[3:0]	o_sd_data;
	input	wire		i_sd_cmd;
	input	wire	[3:0]	i_sd_data;
	input	wire		i_sd_detect;


	//
	// Declaring wishbone master bus data
	//
	wire		wb_cyc, wb_stb, wb_we, wb_stall, wb_err;
	reg	wb_ack;	// ACKs delayed by extra clock
	wire	[(30-1):0]	wb_addr;
	wire	[31:0]	wb_data;
	reg	[31:0]	wb_idata;
	wire	[3:0]	wb_sel;
	wire	sio_sel, sio_stall;
	reg	sio_ack;
	reg	[31:0]	sio_data;
	wire	dio_sel, dio_stall;
	reg	dio_ack;
	reg		pre_dio_ack;
	reg	[31:0]	dio_data;




	//
	// Declaring interrupt lines
	//
	// These declarations come from the various components values
	// given under the @INT.<interrupt name>.WIRE key.
	//
	wire	uarttxf_int;	// uart.INT.UARTTXF.WIRE
	wire	uartrxf_int;	// uart.INT.UARTRXF.WIRE
	wire	uarttx_int;	// uart.INT.UARTTX.WIRE
	wire	uartrx_int;	// uart.INT.UARTRX.WIRE
	wire	w_bus_int;	// buspic.INT.BUS.WIRE
	wire	rtc_int;	// rtc.INT.RTC.WIRE
	wire	flash_interrupt;	// flash.INT.FLASH.WIRE
	wire	zip_cpu_int;	// zip.INT.ZIP.WIRE
	wire	scope_sdcard_int;	// scope_sdcard.INT.SDSCOPE.WIRE
	wire	sdcard_int;	// sdcard.INT.SDCARD.WIRE


	//
	// Declaring Bus-Master data, internal wires and registers
	//
	// These declarations come from the various components values
	// given under the @MAIN.DEFNS key, for those components with
	// an MTYPE flag.
	//
	// ZipSystem/ZipCPU connection definitions
	// All we define here is a set of scope wires
	wire	[31:0]	zip_debug;
	wire		zip_trigger;
	wire		zip_dbg_ack, zip_dbg_stall;
	wire	[31:0]	zip_dbg_data;
	wire	[15:0] zip_int_vector;
	// Definitions for the WB-UART converter.  We really only need one
	// (more) non-bus wire--one to use to select if we are interacting
	// with the ZipCPU or not.
	wire		wbu_zip_sel;
	wire	[0:0]	wbubus_dbg;
`ifndef	INCLUDE_ZIPCPU
	wire		zip_dbg_ack, zip_dbg_stall;
	wire	[31:0]	zip_dbg_data;
`endif


	//
	// Declaring Peripheral data, internal wires and registers
	//
	// These declarations come from the various components values
	// given under the @MAIN.DEFNS key, for those components with a
	// PTYPE key but no MTYPE key.
	//
	// Console definitions
	wire	w_console_rx_stb, w_console_tx_stb, w_console_busy;
	wire	[6:0]	w_console_rx_data, w_console_tx_data;
`include "builddate.v"
	// Definitions in support of the GPS driven RTC
	wire	rtc_ppd;
	reg	r_rtc_ack;
	reg	[31:0]	r_pwrcount_data;
	wire	scope_sdcard_trigger,
		scope_sdcard_ce;
	wire[31:0]	sdspi_debug;


	//
	// Declaring other data, internal wires and registers
	//
	// These declarations come from the various components values
	// given under the @MAIN.DEFNS key, but which have neither PTYPE
	// nor MTYPE keys.
	//
	// Bus arbiter's lines
	wire		dwb_cyc, dwb_stb, dwb_we, dwb_ack, dwb_stall, dwb_err;
	wire	[(30-1):0]	dwb_addr;
	wire	[31:0]	dwb_odata, dwb_idata;
	wire	[3:0]	dwb_sel;


	//
	// Declaring interrupt vector wires
	//
	// These declarations come from the various components having
	// PIC and PIC.MAX keys.
	//
	wire	[14:0]	bus_int_vector;
	wire	[14:0]	sys_int_vector;
	wire	[14:0]	alt_int_vector;

	// Declare those signals necessary to build the bus, and detect
	// bus errors upon it.
	//
	wire	none_sel;
	reg	many_sel, many_ack;
	reg	[31:0]	r_bus_err;

	//
	// Wishbone master wire declarations
	//
	// These are given for every configuration file with an @MTYPE
	// tag, and the names are prefixed by whatever is in the @PREFIX tag.
	//

	wire		zip_cyc, zip_stb, zip_we, zip_ack, zip_stall, zip_err;
	wire	[(30-1):0]	zip_addr;
	wire	[31:0]	zip_data, zip_idata;
	wire	[3:0]	zip_sel;

	wire		wbu_cyc, wbu_stb, wbu_we, wbu_ack, wbu_stall, wbu_err;
	wire	[(30-1):0]	wbu_addr;
	wire	[31:0]	wbu_data, wbu_idata;
	wire	[3:0]	wbu_sel;


	//
	// Wishbone slave wire declarations
	//
	// These are given for every configuration file with a @PTYPE
	// tag, and the names are given by the @PREFIX tag.
	//

	wire	uart_ack, uart_stall, uart_sel;
	wire	[31:0]	uart_data;

	wire	version_ack, version_stall, version_sel;
	wire	[31:0]	version_data;

	wire	flctl_ack, flctl_stall, flctl_sel;
	wire	[31:0]	flctl_data;

	wire	buspic_ack, buspic_stall, buspic_sel;
	wire	[31:0]	buspic_data;

	wire	rtc_ack, rtc_stall, rtc_sel;
	wire	[31:0]	rtc_data;

	wire	bkram_ack, bkram_stall, bkram_sel;
	wire	[31:0]	bkram_data;

	wire	flash_ack, flash_stall, flash_sel;
	wire	[31:0]	flash_data;

	wire	buserr_ack, buserr_stall, buserr_sel;
	wire	[31:0]	buserr_data;

	wire	date_ack, date_stall, date_sel;
	wire	[31:0]	date_data;

	wire	pwrcount_ack, pwrcount_stall, pwrcount_sel;
	wire	[31:0]	pwrcount_data;

	wire	scope_sdcard_ack, scope_sdcard_stall, scope_sdcard_sel;
	wire	[31:0]	scope_sdcard_data;

	wire	sdcard_ack, sdcard_stall, sdcard_sel;
	wire	[31:0]	sdcard_data;


	// Wishbone peripheral address decoding
	// This particular address decoder decodes addresses for all
	// peripherals (components with a @PTYPE tag), based upon their
	// NADDR (number of addresses required) tag
	//

	wire	[2:0]	sio_skip; // bits 0000001c, sbaw=3
	assign	sio_skip = {
			wb_addr[ 2: 0]
		};
	assign	      buserr_sel = (sio_sel)&&(sio_skip[ 2: 0] ==  3'b000_);
	assign	      buspic_sel = (sio_sel)&&(sio_skip[ 2: 0] ==  3'b001_);
	assign	        date_sel = (sio_sel)&&(sio_skip[ 2: 0] ==  3'b010_);
	assign	    pwrcount_sel = (sio_sel)&&(sio_skip[ 2: 0] ==  3'b011_);
	assign	     version_sel = (sio_sel)&&(sio_skip[ 2: 0] ==  3'b100_);
	wire	[0:0]	dio_skip; // bits 00000020, sbaw=3
	assign	dio_skip = {
			wb_addr[3]
		};
	assign	      sdcard_sel = (dio_sel)&&(dio_skip[ 0: 0] ==  1'b0_);
	assign	         rtc_sel = (dio_sel)&&(dio_skip[ 0: 0] ==  1'b1_);
	wire	[6:0]	wb_skip; // bits 011004f0, sbaw=23
	assign	wb_skip = {
			wb_addr[22],
			wb_addr[18],
			wb_addr[8],
			wb_addr[ 5: 2]
		};
	assign	scope_sdcard_sel = ( wb_skip[ 6: 0] ==  7'b001_1000_);
	assign	       flctl_sel = ( wb_skip[ 6: 0] ==  7'b001_1001_);
	assign	        uart_sel = ( wb_skip[ 6: 0] ==  7'b001_1010_);
	assign	       bkram_sel = ( wb_skip[ 6: 5] ==  2'b01);
	assign	       flash_sel = ( wb_skip[ 6: 6] ==  1'b1);
	assign	         dio_sel = ( wb_skip[ 6: 2] ==  5'b001_01);
	assign	         sio_sel = ( wb_skip[ 6: 1] ==  6'b001_000);
	assign	none_sel = (wb_stb)&&({ sio_sel, dio_sel, flash_sel, bkram_sel, uart_sel, flctl_sel, scope_sdcard_sel} == 0);
	//
	// many_sel
	//
	// This should *never* be true .... unless the address decoding logic
	// is somehow broken.  Given that a computer is generating the
	// addresses, that should never happen.  However, since it has
	// happened to me before (without the computer), I test/check for it
	// here.
	//
	// Devices are placed here as a natural result of the address
	// decoding logic.  Thus, any device with a sel_ line will be
	// tested here.
	//
`ifdef	VERILATOR

	always @(*)
		case({sio_sel, dio_sel, flash_sel, bkram_sel, uart_sel, flctl_sel, scope_sdcard_sel})
			7'h0: many_sel = 1'b0;
			7'b1000000: many_sel = 1'b0;
			7'b0100000: many_sel = 1'b0;
			7'b0010000: many_sel = 1'b0;
			7'b0001000: many_sel = 1'b0;
			7'b0000100: many_sel = 1'b0;
			7'b0000010: many_sel = 1'b0;
			7'b0000001: many_sel = 1'b0;
			default: many_sel = (wb_stb);
		endcase

`else	// VERILATOR

	always @(*)
		case({sio_sel, dio_sel, flash_sel, bkram_sel, uart_sel, flctl_sel, scope_sdcard_sel})
			7'h0: many_sel <= 1'b0;
			7'b1000000: many_sel <= 1'b0;
			7'b0100000: many_sel <= 1'b0;
			7'b0010000: many_sel <= 1'b0;
			7'b0001000: many_sel <= 1'b0;
			7'b0000100: many_sel <= 1'b0;
			7'b0000010: many_sel <= 1'b0;
			7'b0000001: many_sel <= 1'b0;
			default: many_sel <= (wb_stb);
		endcase

`endif	// VERILATOR

	//
	// many_ack
	//
	// It is also a violation of the bus protocol to produce multiply
	// acks at once and on the same clock.  In that case, the bus
	// can't decide which result to return.  Worse, if someone is waiting
	// for a return value, that value will never come since another ack
	// masked it.
	//
	// The other error that isn't tested for here, no would I necessarily
	// know how to test for it, is when peripherals return values out of
	// order.  Instead, I propose keeping that from happening by
	// guaranteeing, in software, that two peripherals are not accessed
	// immediately one after the other.
	//
	always @(posedge i_clk)
		case({sio_ack, dio_ack, flash_ack, bkram_ack, uart_ack, flctl_ack, scope_sdcard_ack})
			7'h0: many_ack <= 1'b0;
			7'b1000000: many_ack <= 1'b0;
			7'b0100000: many_ack <= 1'b0;
			7'b0010000: many_ack <= 1'b0;
			7'b0001000: many_ack <= 1'b0;
			7'b0000100: many_ack <= 1'b0;
			7'b0000010: many_ack <= 1'b0;
			7'b0000001: many_ack <= 1'b0;
		default: many_ack <= (wb_cyc);
		endcase
	//
	// wb_ack
	//
	// The returning wishbone ack is equal to the OR of every component that
	// might possibly produce an acknowledgement, gated by the CYC line.  To
	// add new components, OR their acknowledgements in here.
	//
	// To return an ack here, a component must have a @PTYPE.  Acks from
	// any @PTYPE SINGLE and DOUBLE components have been collected
	// together into sio_ack and dio_ack respectively, which will appear.
	// ahead of any other device acks.
	//
	always @(posedge i_clk)
		sio_ack <= (wb_stb)&&(sio_sel);
	always @(posedge i_clk)
		pre_dio_ack <= (wb_stb)&&(dio_sel);
	always @(posedge i_clk)
		dio_ack <= pre_dio_ack;
	always @(posedge i_clk)
		wb_ack <= (wb_cyc)&&(|{sio_ack, dio_ack, flash_ack, bkram_ack, uart_ack, flctl_ack, scope_sdcard_ack});


	//
	// wb_stall
	//
	// The returning wishbone stall line really depends upon what device
	// is requested.  Thus, if a particular device is selected, we return 
	// the stall line for that device.
	//
	// Stall lines come from any component with a @PTYPE key and a
	// @NADDR > 0.  Since those components of @PTYPE SINGLE or DOUBLE
	// are not allowed to stall, they have been removed from this list
	// here for simplicity.
	//
	assign	sio_stall = 1'b0;
	assign	dio_stall = 1'b0;
	assign	wb_stall = 
		  (wb_stb)&&(scope_sdcard_sel)&&(scope_sdcard_stall)
		||(wb_stb)&&( flctl_sel)&&( flctl_stall)
		||(wb_stb)&&(  uart_sel)&&(  uart_stall)
		||(wb_stb)&&( bkram_sel)&&( bkram_stall)
		||(wb_stb)&&( flash_sel)&&( flash_stall)
		||(wb_stb)&&(   dio_sel)&&(   dio_stall)
		||(wb_stb)&&(   sio_sel)&&(   sio_stall);


	//
	// wb_err
	//
	// This is the bus error signal.  It should never be true, but practice
	// teaches us otherwise.  Here, we allow for three basic errors:
	//
	// 1. STB is true, but no devices are selected
	//
	//	This is the null pointer reference bug.  If you try to access
	//	something on the bus, at an address with no mapping, the bus
	//	should produce an error--such as if you try to access something
	//	at zero.
	//
	// 2. STB is true, and more than one device is selected
	//
	//	(This can be turned off, if you design this file well.  For
	//	this line to be true means you have a design flaw.)
	//
	// 3. If more than one ACK is every true at any given time.
	//
	//	This is a bug of bus usage, combined with a subtle flaw in the
	//	WB pipeline definition.  You can issue bus requests, one per
	//	clock, and if you cross device boundaries with your requests,
	//	you may have things come back out of order (not detected here)
	//	or colliding on return (detected here).  The solution to this
	//	problem is to make certain that any burst request does not cross
	//	device boundaries.  This is a requirement of whoever (or
	//	whatever) drives the bus.
	//
	assign	wb_err = ((wb_stb)&&(none_sel || many_sel))
				|| ((wb_cyc)&&(many_ack));

	always @(posedge i_clk)
		if (wb_err)
			r_bus_err <= { wb_addr, 2'b00 };

	//Now we turn to defining all of the parts and pieces of what
	// each of the various peripherals does, and what logic it needs.
	//
	// This information comes from the @MAIN.INSERT and @MAIN.ALT tags.
	// If an @ACCESS tag is available, an ifdef is created to handle
	// having the access and not.  If the @ACCESS tag is `defined above
	// then the @MAIN.INSERT code is executed.  If not, the @MAIN.ALT
	// code is exeucted, together with any other cleanup settings that
	// might need to take place--such as returning zeros to the bus,
	// or making sure all of the various interrupt wires are set to
	// zero if the component is not included.
	//
	//
	// Declare the interrupt busses
	//
	assign	bus_int_vector = {
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		sdcard_int,
		flash_interrupt
	};
	assign	sys_int_vector = {
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		sdcard_int,
		uartrxf_int,
		uarttxf_int,
		w_bus_int,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0
	};
	assign	alt_int_vector = {
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		rtc_int,
		uartrx_int,
		uarttx_int,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0
	};
`ifdef	BUSCONSOLE_ACCESS
	wbconsole console(i_clk, 1'b0,
 			wb_cyc, (wb_stb)&&(uart_sel), wb_we,
				wb_addr[1:0], wb_data,
 			uart_ack, uart_stall, uart_data,
			w_console_tx_stb, w_console_tx_data, w_console_busy,
			w_console_rx_stb, w_console_rx_data,
			uartrx_int, uarttx_int, uartrxf_int, uarttxf_int);
`else	// BUSCONSOLE_ACCESS

	reg	r_uart_ack;
	always @(posedge i_clk)
		r_uart_ack <= (wb_stb)&&(uart_sel);

	assign	uart_ack   = r_uart_ack;
	assign	uart_stall = 1'b0;
	assign	uart_data  = 32'h0;

	assign	uarttxf_int = 1'b0;	// uart.INT.UARTTXF.WIRE
	assign	uartrxf_int = 1'b0;	// uart.INT.UARTRXF.WIRE
	assign	uarttx_int = 1'b0;	// uart.INT.UARTTX.WIRE
	assign	uartrx_int = 1'b0;	// uart.INT.UARTRX.WIRE
`endif	// BUSCONSOLE_ACCESS

	assign	version_data = `DATESTAMP;
	assign	version_ack = 1'b0;
	assign	version_stall = 1'b0;
`ifdef	FLASH_ACCESS
	// The Flash control interface result comes back together with the
	// flash interface itself.  Hence, we always return zero here.
	assign	flctl_ack   = 1'b0;
	assign	flctl_stall = 1'b0;
	assign	flctl_data  = 0;
`else	// FLASH_ACCESS

	reg	r_flctl_ack;
	always @(posedge i_clk)
		r_flctl_ack <= (wb_stb)&&(flctl_sel);

	assign	flctl_ack   = r_flctl_ack;
	assign	flctl_stall = 1'b0;
	assign	flctl_data  = 32'h0;

`endif	// FLASH_ACCESS

`ifdef	BUSPIC_ACCESS
	//
	// The BUS Interrupt controller
	//
	icontrol #(15)	buspic(i_clk, 1'b0, (wb_stb)&&(buspic_sel),
			wb_data, buspic_data, bus_int_vector, w_bus_int);
`else	// BUSPIC_ACCESS

	reg	r_buspic_ack;
	always @(posedge i_clk)
		r_buspic_ack <= (wb_stb)&&(buspic_sel);

	assign	buspic_ack   = r_buspic_ack;
	assign	buspic_stall = 1'b0;
	assign	buspic_data  = 32'h0;

	assign	w_bus_int = 1'b0;	// buspic.INT.BUS.WIRE
`endif	// BUSPIC_ACCESS

	//
	//
	// And an arbiter to decide who gets access to the bus
	//
	//
	wbpriarbiter #(32,30)	bus_arbiter(i_clk,
		// The Zip CPU bus master --- gets the priority slot
		zip_cyc, zip_stb, zip_we, zip_addr, zip_data, zip_sel,
			zip_ack, zip_stall, zip_err,
		// The UART interface master
		(wbu_cyc)&&(!wbu_zip_sel), (wbu_stb)&&(!wbu_zip_sel), wbu_we,
			wbu_addr[(30-1):0], wbu_data, wbu_sel,
			wbu_ack, wbu_stall, wbu_err,
		// Common bus returns
		dwb_cyc, dwb_stb, dwb_we, dwb_addr, dwb_odata, dwb_sel,
			dwb_ack, dwb_stall, dwb_err);

	// And because the ZipCPU and the Arbiter can create an unacceptable
	// delay, we often fail timing.  So, we add in a delay cycle
`ifdef	WBUBUS_MASTER
`ifdef	INCLUDE_ZIPCPU
`define	BUS_DELAY_NEEDED
`endif
`endif
`ifdef	BUS_DELAY_NEEDED
	busdelay #(30)	dwb_delay(i_clk,
		dwb_cyc, dwb_stb, dwb_we, dwb_addr, dwb_odata, dwb_sel,
			dwb_ack, dwb_stall, dwb_idata, dwb_err,
		wb_cyc, wb_stb, wb_we, wb_addr, wb_data, wb_sel,
			wb_ack, wb_stall, wb_idata, wb_err);
`else
	// If one of the two, the ZipCPU or the WBUBUS, isn't here, then we
	// don't need the bus delay, and we can go directly from the bus driver
	// to the bus itself
	//
	assign	wb_cyc    = dwb_cyc;
	assign	wb_stb    = dwb_stb;
	assign	wb_we     = dwb_we;
	assign	wb_addr   = dwb_addr;
	assign	wb_data   = dwb_odata;
	assign	wb_sel    = dwb_sel;
	assign	dwb_ack   = wb_ack;
	assign	dwb_stall = wb_stall;
	assign	dwb_err   = wb_err;
	assign	dwb_idata = wb_idata;
`endif
	assign	wbu_idata = dwb_idata;
	assign	zip_idata = dwb_idata;
`ifdef	RTC_ACCESS
	rtclight	#(32'h002af31d) thertc(i_clk,
		wb_cyc, (wb_stb)&&(rtc_sel), wb_we,
			wb_addr[2:0], wb_data,
		rtc_data, rtc_int, rtc_ppd);
	initial	r_rtc_ack = 1'b0;
	always @(posedge i_clk)
		r_rtc_ack <= (wb_stb)&&(rtc_sel);
	assign	rtc_ack = r_rtc_ack;
`else	// RTC_ACCESS

	reg	r_rtc_ack;
	always @(posedge i_clk)
		r_rtc_ack <= (wb_stb)&&(rtc_sel);

	assign	rtc_ack   = r_rtc_ack;
	assign	rtc_stall = 1'b0;
	assign	rtc_data  = 32'h0;

	assign	rtc_int = 1'b0;	// rtc.INT.RTC.WIRE
`endif	// RTC_ACCESS

`ifdef	BLKRAM_ACCESS
	memdev #(.LGMEMSZ(20), .EXTRACLOCK(1))
		bkrami(i_clk,
			(wb_cyc), (wb_stb)&&(bkram_sel), wb_we,
				wb_addr[(20-3):0], wb_data, wb_sel,
				bkram_ack, bkram_stall, bkram_data);
`else	// BLKRAM_ACCESS

	reg	r_bkram_ack;
	always @(posedge i_clk)
		r_bkram_ack <= (wb_stb)&&(bkram_sel);

	assign	bkram_ack   = r_bkram_ack;
	assign	bkram_stall = 1'b0;
	assign	bkram_data  = 32'h0;

`endif	// BLKRAM_ACCESS

`ifdef	FLASH_ACCESS
	wbqspiflash #(24)
		flashmem(i_clk,
			(wb_cyc), (wb_stb)&&(flash_sel), (wb_stb)&&(flctl_sel),wb_we,
			wb_addr[(24-3):0], wb_data,
			flash_ack, flash_stall, flash_data,
			o_qspi_sck, o_qspi_cs_n, o_qspi_mod, o_qspi_dat, i_qspi_dat,
			flash_interrupt);
`else	// FLASH_ACCESS
	assign	o_qspi_sck  = 1'b1;
	assign	o_qspi_cs_n = 1'b1;
	assign	o_qspi_mod  = 2'b01;
	assign	o_qspi_dat  = 4'b1111;

	reg	r_flash_ack;
	always @(posedge i_clk)
		r_flash_ack <= (wb_stb)&&(flash_sel);

	assign	flash_ack   = r_flash_ack;
	assign	flash_stall = 1'b0;
	assign	flash_data  = 32'h0;

	assign	flash_interrupt = 1'b0;	// flash.INT.FLASH.WIRE
`endif	// FLASH_ACCESS

	assign	buserr_data = r_bus_err;
`ifdef	INCLUDE_ZIPCPU
	//
	//
	// The ZipCPU/ZipSystem BUS master
	//
	//
`ifndef	WBUBUS_MASTER
	wire	wbu_zip_sel;
	assign	wbu_zip_sel = 1'b0;
`endif
	assign	zip_int_vector = { alt_int_vector[14:8], sys_int_vector[14:6] };
	zipsystem #(RESET_ADDRESS,ZIP_ADDRESS_WIDTH,10,ZIP_START_HALTED,ZIP_INTS)
		swic(i_clk, i_cpu_reset,
			// Zippys wishbone interface
			zip_cyc, zip_stb, zip_we, zip_addr, zip_data, zip_sel,
					zip_ack, zip_stall, zip_idata, zip_err,
			zip_int_vector, zip_cpu_int,
			// Debug wishbone interface
			((wbu_cyc)&&(wbu_zip_sel)),
			((wbu_stb)&&(wbu_zip_sel)),wbu_we, wbu_addr[0],
			wbu_data, zip_dbg_ack, zip_dbg_stall, zip_dbg_data,
			zip_debug);
	assign	zip_trigger = zip_debug[0];
`else	// INCLUDE_ZIPCPU

	assign	zip_cyc = 1'b0;
	assign	zip_stb = 1'b0;
	assign	zip_we  = 1'b0;
	assign	zip_sel = 4'b0000;
	assign	zip_addr = 0;
	assign	zip_data = 0;

	assign	zip_cpu_int = 1'b0;	// zip.INT.ZIP.WIRE
`endif	// INCLUDE_ZIPCPU

`ifdef	RTCDATE_ACCESS
	//
	// The Calendar DATE
	//
	rtcdate	thedate(i_clk, rtc_ppd,
		(wb_stb)&&(date_sel), wb_we, wb_data,
			date_ack, date_stall, date_data);
`else	// RTCDATE_ACCESS

	reg	r_date_ack;
	always @(posedge i_clk)
		r_date_ack <= (wb_stb)&&(date_sel);

	assign	date_ack   = r_date_ack;
	assign	date_stall = 1'b0;
	assign	date_data  = 32'h0;

`endif	// RTCDATE_ACCESS

	initial	r_pwrcount_data = 32'h0;
	always @(posedge i_clk)
	if (r_pwrcount_data[31])
		r_pwrcount_data[30:0] <= r_pwrcount_data[30:0] + 1'b1;
	else
		r_pwrcount_data[31:0] <= r_pwrcount_data[31:0] + 1'b1;
	assign	pwrcount_data = r_pwrcount_data;
`ifdef	WBUBUS_MASTER
`ifdef	INCLUDE_ZIPCPU
	assign	wbu_zip_sel   = wbu_addr[29];
`else
	assign	wbu_zip_sel   = 1'b0;
	assign	zip_dbg_ack   = 1'b0;
	assign	zip_dbg_stall = 1'b0;
	assign	zip_dbg_data  = 0;
`endif
`ifndef	BUSPIC_ACCESS
	wire	w_bus_int;
	assign	w_bus_int = 1'b0;
`endif
	wire	[31:0]	wbu_tmp_addr;
	wbuconsole genbus(i_clk, i_host_rx_stb, i_host_rx_data,
			wbu_cyc, wbu_stb, wbu_we, wbu_tmp_addr, wbu_data,
			(wbu_zip_sel)?zip_dbg_ack:wbu_ack,
			(wbu_zip_sel)?zip_dbg_stall:wbu_stall,
				(wbu_zip_sel)?1'b0:wbu_err,
				(wbu_zip_sel)?zip_dbg_data:wbu_idata,
			w_bus_int,
			o_host_tx_stb, o_host_tx_data, i_host_tx_busy,
			//
			w_console_tx_stb, w_console_tx_data, w_console_busy,
			w_console_rx_stb, w_console_rx_data,
			//
			wbubus_dbg[0]);
	assign	wbu_sel = 4'hf;
	assign	wbu_addr = wbu_tmp_addr[(30-1):0];
`else	// WBUBUS_MASTER

	assign	wbu_cyc = 1'b0;
	assign	wbu_stb = 1'b0;
	assign	wbu_we  = 1'b0;
	assign	wbu_sel = 4'b0000;
	assign	wbu_addr = 0;
	assign	wbu_data = 0;

`endif	// WBUBUS_MASTER

`ifdef	SDSPI_SCOPE
	assign	scope_sdcard_trigger = (wb_stb)
				&&(sdcard_sel)&&(wb_we);
	assign	scope_sdcard_ce = 1'b1;
	wbscope #(5'h9) sdspiscope(i_clk, scope_sdcard_ce,
			scope_sdcard_trigger,
			sdspi_debug,
			i_clk, wb_cyc,
			(wb_stb)&&(scope_sdcard_sel),
			wb_we,
			wb_addr[0],
			wb_data,
			scope_sdcard_ack,
			scope_sdcard_stall,
			scope_sdcard_data,
			scope_sdcard_int);

`else	// SDSPI_SCOPE

	reg	r_scope_sdcard_ack;
	always @(posedge i_clk)
		r_scope_sdcard_ack <= (wb_stb)&&(scope_sdcard_sel);

	assign	scope_sdcard_ack   = r_scope_sdcard_ack;
	assign	scope_sdcard_stall = 1'b0;
	assign	scope_sdcard_data  = 32'h0;

	assign	scope_sdcard_int = 1'b0;	// scope_sdcard.INT.SDSCOPE.WIRE
`endif	// SDSPI_SCOPE

`ifdef	SDSPI_ACCESS
	// SPI mapping
	wire	w_sd_cs_n, w_sd_mosi, w_sd_miso;

	sdspi	sdcardi(i_clk,
		wb_cyc,
			(wb_stb)&&(sdcard_sel),
			wb_we,
			wb_addr[1:0],
			wb_data,
			sdcard_ack, sdcard_stall, sdcard_data,
		w_sd_cs_n, o_sd_sck, w_sd_mosi, w_sd_miso,
		sdcard_int, 1'b1, sdspi_debug);

	assign	w_sd_miso = i_sd_data[0];
	assign	o_sd_data = { w_sd_cs_n, 3'b111 };
	assign	o_sd_cmd  = w_sd_mosi;
`else	// SDSPI_ACCESS
	assign	o_sd_sck   = 1'b1;
	assign	o_sd_cmd   = 1'b1;
	assign	o_sd_data  = 4'hf;

	reg	r_sdcard_ack;
	always @(posedge i_clk)
		r_sdcard_ack <= (wb_stb)&&(sdcard_sel);

	assign	sdcard_ack   = r_sdcard_ack;
	assign	sdcard_stall = 1'b0;
	assign	sdcard_data  = 32'h0;

	assign	sdcard_int = 1'b0;	// sdcard.INT.SDCARD.WIRE
`endif	// SDSPI_ACCESS

	//
	// Finally, determine what the response is from the wishbone
	// bus
	//
	//
	//
	// wb_idata
	//
	// This is the data returned on the bus.  Here, we select between a
	// series of bus sources to select what data to return.  The basic
	// logic is simply this: the data we return is the data for which the
	// ACK line is high.
	//
	// The last item on the list is chosen by default if no other ACK's are
	// true.  Although we might choose to return zeros in that case, by
	// returning something we can skimp a touch on the logic.
	//
	// Any peripheral component with a @PTYPE value will be listed
	// here.
	//
	always @(posedge i_clk)
	casez({ buserr_sel, buspic_sel, date_sel, pwrcount_sel, version_sel })
		 5'b1????: sio_data <= buserr_data;
		 5'b01???: sio_data <= buspic_data;
		 5'b001??: sio_data <= date_data;
		 5'b0001?: sio_data <= pwrcount_data;
		 5'b00001: sio_data <= version_data;
		default: sio_data <= 32'h0;
	endcase

	always @(posedge i_clk)
	casez({ sdcard_ack, rtc_ack })
		 2'b1?: dio_data <= sdcard_data;
		 2'b01: dio_data <= rtc_data;
		default: dio_data <= 32'h0;
	endcase
	always @(posedge i_clk)
	begin
		casez({ sio_ack, dio_ack, flash_ack, bkram_ack, uart_ack, flctl_ack, scope_sdcard_ack })
			7'b1??????: wb_idata <= sio_data;
			7'b01?????: wb_idata <= dio_data;
			7'b001????: wb_idata <= flash_data;
			7'b0001???: wb_idata <= bkram_data;
			7'b00001??: wb_idata <= uart_data;
			7'b000001?: wb_idata <= flctl_data;
			7'b0000001: wb_idata <= scope_sdcard_data;
			default: wb_idata <= 32'h0;
		endcase
	end


endmodule // main.v
